### ISSUE TITLE
W1L3 MB : Some weakpoints do not rotate

### ISSUE THREAD

**Issue by cguillaume44** [cguillaume44/Outshine-Issues#82] opened 2022-04-07 09:47 UTC
1. Die in the level
2. retry until mini boss
3. Check if all weakpoints are rotating

Build 1107

https://user-images.githubusercontent.com/51667183/162171097-a8a1cfeb-4ceb-4548-bcb3-c50dc1c653f9.mp4

**Comment by guillaumeDerudder** [comment] 2022-04-11 13:14
Duplicate of #79

**Closed by guillaumeDerudder** 2022-04-11 13:14 UTC
Labels: Bug B
