### ISSUE TITLE
The "Disappearance of Words" modifier doesn't work properly after restarting a level

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#52] opened 2022-03-15 11:45 UTC
Description:
Some words won't fade after restarting a level that has the "Disappearance of Words" modifier. Please note that this issue occurs only after manually restarting a level from the "Pause menu". 
The reproduction rate for this issue is 3/10 - 30%.

1. Boot the title
2. Start any level with the "Disappearance of Words" modifier
3. Open the "Pause Menu"
4. Press the "Retry" button
5. Progress through the level
6. Notice that some words won't fade after retrying the level

Expected behavior
Modifiers should be functional after restarting any level.

Video: https://user-images.githubusercontent.com/101404099/158371036-73095c98-c7cb-4213-b28f-9dae9ed459b8.mp4

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8252903/Player.log)

**Comment by LeanderSimonart** [comment] 2022-03-23 13:51
The origin of this issue could be rooted in the same thing as issue #44 

We were not resetting the IsBeingTyped variable if the word dissapeared while it was being typed and the IsBeingTyped variable forces the default alpha value. So the next time we use the same enemy it was still marked as IsBeingTyped even if it wasn't.
So this issue might already be fixed.

**Comment by MaxDaniels** [comment] 2022-03-29 13:49
Can't reproduce with current code.

**Closed** 2022-04-14 07:46 UTC
Labels: Bug C, Can't reproduce
